### ISSUE TITLE
Handle Connection Lifetime Events

### ISSUE THREAD

**Issue by chetjan** [chetjan/heisenslaught#29]
There are corner cases with flaky connections that we do not handle. For example if a client reconnects for long enough that the server calls `OnDisconnect`, then if the connection is reestablished the client will receive a Stop event. In this stop event we have handle restarting the connection so that the client can seamlessly get the update draft.

**Comment by chetjan** [comment]
Please reference: https://www.asp.net/signalr/overview/guide-to-the-api/handling-connection-lifetime-events for Connection Lifetimes.

**Comment by myrddraall** [comment]
done in pr #31
