### ISSUE TITLE
Show number of users connected to the draft

### ISSUE THREAD

**Issue by myrddraall** [chetjan/heisenslaught#34]

**Comment by chetjan** [comment]
If possible I would also like to see the names of who has connected. We could either prompt the obs for a name entry or push this down the line to when we have some for of user account.

**Comment by myrddraall** [comment]
yeah i was thinking of waiting until we did a login, once we get usernames we can also consider simple chat. We could put in a prompt but i didn't really like the experience

**Comment by myrddraall** [comment]
done in PR #44
