### ISSUE TITLE
Searchbar skinning and role filter

### ISSUE THREAD

**Issue by myrddraall** [chetjan/heisenslaught#35]

**Comment by myrddraall** [comment]
So what role buttons do we want to include for quick filtering?

we have 14 roles
  - ambusher
  - assassin
  - bruiser
  - burst
  - global
  - healer
  - melee
  - multi-class
  - ranged
  - seige
  - specialist
  - sustain
  - support
  - tank

I think we can leave out:
  - melee
  - multi-class
  - ranged
  - specialist

which leaves us with 10 buttons. is that to much? It also a lot of icons that are not available in the game files.
Is there an alternate ui element we could use? (I don't like the idea of a multi select box)

**Comment by myrddraall** [comment]
Maybe we can come up with some meta roles that encompass multiple role tags

**Comment by myrddraall** [comment]
Thinking about it some more i think we might be good with the following as buttons: 
  - tank
  - bruiser
  - burst
  - sustain
  - healer
  - support
  - siege
  
the text search can always be used to refine the filter further

**Comment by chetjan** [comment]
I agree that those buttons would be sufficient for most cases, but I worry about discoverability for the rest of the terms (for example global). Maybe we could include a question mark icon next to the search box which when hovered explained what was searched and a list of roles? (We can create a separate ticket for the question mark icon if you think it is appropriate.)

**Comment by myrddraall** [comment]
done in #49

**Comment by myrddraall** [comment]
> We can create a separate ticket for the question mark icon if you think it is appropriate.

yeah i think a separate ticket is in order

**Comment by chetjan** [comment]
Sounds good. https://github.com/chetjan/heisenslaught/issues/50
