### ISSUE TITLE
Hero portraits do not appear in Edge

### ISSUE THREAD

**Issue by chetjan** [chetjan/heisenslaught#45]
In Edge the hero portraits for selection do not appear until they are hovered over.

**Comment by myrddraall** [comment]
Strange, they used to work and that's the one state I did't modify. On min they only show when clicked. not even when hovered

**Comment by myrddraall** [comment]
really ms... really?!?  Apparently the img tag and the image tag are the same thing in css to edge

**Comment by myrddraall** [comment]
Fixed in #46

**Comment by chetjan** [comment]
Ha, nice catch.
