### ISSUE TITLE
User Login

### ISSUE THREAD

**Issue by chetjan** [chetjan/heisenslaught#48]
Going to use ASP Identity. (MongoDB store provider linked from aspnet/identity GitHub https://github.com/tugberkugurlu/AspNetCore.Identity.MongoDB)

**Comment by myrddraall** [comment]
does identity support things like google+/facebook login integration or is it a standalone system?

**Comment by chetjan** [comment]
You can have either or both. I am probably going to start with just 3rd party login.

**Comment by myrddraall** [comment]
do you wanna handle the ui as well or should we split it up?

**Comment by chetjan** [comment]
I think the UI will be very minimal and I don't know how the api will look yet, so I'll keep it as one ticket for now.

**Comment by myrddraall** [comment]
https://dev.battle.net/docs

have you seen this? might make sense to have people login using battle.net

**Comment by chetjan** [comment]
I had not thought of that, good idea. I'll take a look.

**Comment by myrddraall** [comment]
@chetjan 
I've got an initial implementation in the [Identity Branch](https://github.com/myrddraall/heisenslaught/tree/identity). It's using battle.net as the identity provider.
It requires https to work. check it out when you have the chance and let me know what you think. 
I haven't had the chance to add instructions yet but i'll add those shortly

**Comment by chetjan** [comment]
Neat, it looks good. I'll get started with Let's Encrypt to get us a certificate.
