### ISSUE TITLE
Material Components Integration

### ISSUE THREAD

**Issue by chetjan** [chetjan/heisenslaught#6]
We do not want to include the full jQuery library (see https://scotch.io/tutorials/how-to-correctly-use-bootstrapjs-and-angularjs-together), but I would like to include Bootstrap for some simple styling of components. I believe https://ng-bootstrap.github.io/#/home will allow us to achieve this, as well as keep our current Sass compilation process.

**Comment by myrddraall** [comment]
evaluate:
http://valor-software.com/ng2-bootstrap/#/ vs https://material.angular.io/

material is by the angular team but isn't quite as far along in dev

**Comment by myrddraall** [comment]
https://ng-bootstrap.github.io/
http://www.primefaces.org/primeng/
https://teradata.github.io/covalent

**Comment by myrddraall** [comment]
Did some more research on Covalent. It's built on material 2 so most of the components are martial 2 components. They do however preview all the material 2 components much nicer than the actual martial project

https://teradata.github.io/covalent/#/components/material-components

my preference goes to using material over bootstrap. I've worked a lot with both in the past and the quality, ease of use, responsive layout and ng integration  is superior for material.

**Comment by chetjan** [comment]
Neat, I like that. Let's go with material.

**Comment by myrddraall** [comment]
done in pr #31
