### ISSUE TITLE
Data Persistance

### ISSUE THREAD

**Issue by chetjan** [chetjan/heisenslaught#8]
Persist data to a data store. This may be simplest through the entity framework and a sqlite file for now.

**Comment by myrddraall** [comment]
Might want to consider mongodb. Each draft can essentially be considered a document so storing and retrieving is as simple as serializing/derializing the DraftConfig Object. That way we don't have to mess with table design at all

**Comment by myrddraall** [comment]
done due to bad weather?

[Draft Concurrency & Persistence](https://github.com/myrddraall/heisenslaught/tree/draft_persistance_test)

**Comment by chetjan** [comment]
~Not sure what you mean? Bad weather?~

**Comment by chetjan** [comment]
I see your Discord message now.

**Comment by myrddraall** [comment]
Sorry bad joke ;)

**Comment by myrddraall** [comment]
done in #28
